---
title: "p8105_hw2_xw2676.Rmd"
output: github_document
---

##Problem1
Read and clean the Mr. Trash Wheel sheet:
```{r setup, include=FALSE}
library(readxl)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
Mr.Trash_Wheel = read_excel("./dataset/HealthyHarborWaterWheelTotals2018-7-28.xlsx",sheet = "Mr. Trash Wheel",range = "A2:N338") %>% janitor::clean_names() %>% drop_na(dumpster) %>% mutate(sports_balls = as.integer(round(sports_balls,digits = 0)))
```
Read and clean precipitation data for 2017 and 2018:
```{r}
data_2017 = read_excel("./dataset/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                       sheet = "2017 Precipitation",range = "A2:B14") %>%
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2017)
data_2018 = read_excel("./dataset/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                       sheet = "2018 Precipitation",range = "A2:B14") %>%
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2018)
data_combine = bind_rows(data_2017, data_2018) %>%
  mutate(month=month.name[month])
```
##Problem2
clean the data in pols-month.csv
```{r}
pols_month = read_csv("./dataset/pols-month.csv") %>%
  janitor::clean_names() %>% 
  separate(mon, into = c("year","month","day"), sep = "-")%>%
  mutate(
    year=as.numeric(year),
    month=as.numeric(month),
    month=month.name[month])%>% 
  pivot_longer(
    c("prez_gop","prez_dem"),
    names_to = "president",
    names_prefix = "prez_") %>% 
  filter(value == 1|value == 2) %>% 
  select(-value,-day) 
```
clean the data in snp.csv
```{r}
snp = read_csv("./dataset/snp.csv") %>%
  janitor::clean_names() %>% 
  separate(date, into = c("month","day","year"), sep = "/") %>%
  mutate(
    year = as.numeric(year),
    month = as.numeric(month),
    month = month.name[month]) %>% 
    select(-day) %>% 
    arrange(year,month)
snp = snp[,c(2,1,3)]
```
tidy the unemployment data
```{r}
unemployment = read_csv("./dataset/unemployment.csv") %>%
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment") %>% 
  mutate(
    month = factor(month, 
                   levels =
  c("jan","feb","mar","apr","may","jun","jul","aug","sep","oct","dec","nov"),
                   labels =
  c("1","2","3","4","5","6","7","8","9","10","11","12"))
  ) %>% 
  mutate(
    month = month.name[as.numeric(month)]
  )
```
Join the datasets by merging snp into pols, and merging unemployment into the result.
```{r}
pols_month = unite(pols_month,date,year:month)
snp = unite(snp,date,year:month)
unemployment = unite(unemployment,date,year:month)
join_data = 
  left_join(pols_month, snp, by = "date") %>% 
  left_join(unemployment, by = "date")
```














